name: Build and Deploy to Production

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          # relative path to the place where source code with Dockerfile is located
          context: .
          file: ./Dockerfile
          tags: ghcr.io/rendyproklamanta/kubernetes-nextjs:latest

  deploy-to-kubernetes-cluster:
    name: Deploy to Kubernetes Cluster
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy to Cluster
        uses: myrotvorets/kubectl-action@2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          version: latest
          args: apply -f kubernetes/deploy.yaml

      - name: Rolling Update Image
        uses: myrotvorets/kubectl-action@2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          version: latest
          # Change app-deploy-name to your deployment name $ kubectl get deployments
          args: rollout restart deploy nextjs-app
